
services:
  backend:
    image: backend:safe
    ports:
      - 8082:8080
    environment:
      - POSTGRES_DB=gradproj
    networks:
      - gradproj
  
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gradproj
    environment:
      - POSTGRES_DB=gradproj
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432

  jenkins:
    image: jenkins/jenkins:lts
    platform: linux/amd64
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http jenkins:8080

volumes:
  db-data:
  jenkins-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  gradproj:

